// Generated by CoffeeScript 1.6.1
(function() {
  var build_card, series;

  series = ['xs', 's', 'm', 'l', 'xl', 'xxl', 'oo', 'coffee'];

  build_card = function(value) {
    return $("<div class='card inactive'>").text(value);
  };

  $(function() {
    var $main;
    $main = $("#main");
    series.map(build_card).map(function(x) {
      return $main.append(x);
    });
    $main.on("click", ".card", function() {
      var $reveal;
      $reveal = $("<div class='reveal back'>").text($(this).text());
      $reveal.height(window.innerHeight).width(window.innerWidth);
      $main.append($reveal);
      return false;
    });
    $main.on("click", ".reveal.back", function() {
      var _this = this;
      setTimeout((function() {
        return $(_this).removeClass("back").addClass("front");
      }), 0);
      return false;
    });
    return $main.on("click", ".reveal.front", function() {
      console.log("que si que no");
      $(this).remove();
      return false;
    });
  });

}).call(this);
