// Generated by CoffeeScript 1.6.1
(function() {
  var addStyleForGrid, addStyleForReveal, defer, series;

  series = ['xs', 's', 'm', 'l', 'xl', 'xxl', '∞', 'LP'];

  defer = function(f) {
    return setTimeout(f, 0);
  };

  addStyleForReveal = function() {
    var h, style, w;
    w = window.innerWidth * 0.8;
    h = window.innerHeight * 0.9;
    style = "div.card.reveal {";
    style += "height: " + h + "px;";
    style += "width: " + w + "px;";
    style += "line-height: " + h + "px;";
    style += "font-size: " + (h * 0.5) + "px;";
    style += "}";
    return $("head").append("<style>" + style + "</style>");
  };

  addStyleForGrid = function() {
    var h, style, w;
    w = window.innerWidth * 0.20;
    h = w * 1.5;
    style = "div.card {";
    style += "min-height: " + h + "px;";
    style += "min-width: " + w + "px;";
    style += "line-height: " + h + "px;";
    style += "font-size: " + (h * 0.5) + "px;";
    style += "}";
    return $("head").append("<style>" + style + "</style>");
  };

  $(function() {
    var $main;
    addStyleForReveal();
    addStyleForGrid();
    $main = $("#main");
    series.map(function(value) {
      return $main.append("<div class='card'>" + value + "</div>");
    });
    $main.on("click", ".card", function() {
      var $this;
      $this = $(this);
      $(".card").addClass("hidden");
      $this.removeClass("hidden");
      defer(function() {
        return $this.addClass("reveal back");
      });
      return false;
    });
    $main.on("click", ".reveal.back", function() {
      var _this = this;
      defer(function() {
        return $(_this).removeClass("back").addClass("front");
      });
      return false;
    });
    return $main.on("click", ".reveal.front", function() {
      var $this;
      $this = $(this);
      $(".card").removeClass("hidden");
      defer(function() {
        return $this.removeClass("reveal back front");
      });
      return false;
    });
  });

}).call(this);
